services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: absen_digital
      MYSQL_ROOT_PASSWORD: delapanbelas
      MYSQL_USER: dbabsen
      MYSQL_PASSWORD: absensmk2026
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=dbabsen
      - DB_PASSWORD=absensmk2026
      - DB_NAME=absen_digital
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/backend/uploads

volumes:
  mysql_data:
